### PR TITLE
fix: .git* files not included

### LINKED ISSUE #1928: Python package build Issue with version >= `0.48`
Hello Team,

i am facing an issue due to https://github.com/prefix-dev/rattler-build/pull/1838. 

Until `0.47` the `.git` folder was copied to the build and using  https://setuptools-scm.readthedocs.io/en/latest/ was working fine. Now the builds are failing since the git repository could not be found at the build location.

Question, how do i ensure that the `.git` folder is copied during the build so that the build works as usual. (the version for the package is set dynamic and is parsed by setuptools_scm during build time)

a sample `build.sh` where this fails 

```
git restore .
unset CMAKE_GENERATOR && $PYTHON install.py wheel
$PYTHON -m pip install dist/my-pkg*.whl
```

e.g this is the error that i get now (the same works without any issue with `v < 0.48`)

```
Processing $SRC_DIR
│ │   Preparing metadata (pyproject.toml): started
│ │   Running command Preparing metadata (pyproject.toml)
│ │   Traceback (most recent call last):
│ │     File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
│ │       main()
│ │     File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
│ │       json_out["return_val"] = hook(**hook_input["kwargs"])
│ │                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 175, in prepare_metadata_for_build_wheel
│ │       return hook(metadata_directory, config_settings)
│ │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/build/__init__.py", line 96, in prepare_metadata_for_build_wheel
│ │       return _build_wheel_impl(
│ │              ^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/build/wheel.py", line 176, in _build_wheel_impl
│ │       return _build_wheel_impl_impl(
│ │              ^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/build/wheel.py", line 233, in _build_wheel_impl_impl
│ │       metadata = get_standard_metadata(pyproject, settings)
│ │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/build/metadata.py", line 44, in get_standard_metadata
│ │       new_pyproject_dict["project"] = process_dynamic_metadata(
│ │                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/builder/_load_provider.py", line 150, in process_dynamic_metadata
│ │       return dict(settings)
│ │              ^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/builder/_load_provider.py", line 114, in __getitem__
│ │       self.project[key] = provider.dynamic_metadata(  # type: ignore[call-arg]
│ │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ │     File "$PREFIX/lib/python3.12/site-packages/scikit_build_core/metadata/setuptools_scm.py", line 46, in dynamic_metadata
│ │       raise ValueError(msg)
│ │   ValueError: setuptools-scm was unable to detect version for $SRC_DIR.
```

### LINKED ISSUE #1982: rattler-build doesn't include files in `.github` in `$PREFIX`
```yml
package:
  name: foo
  version: 1.0.0

build:
  script: |
    ! test -f $PREFIX/.github/foo
    mkdir -p $PREFIX/.github/
    echo abc > $PREFIX/.github/foo
    test -f $PREFIX/.github/foo

tests:
  - package_contents:
      files:
        - .github/foo
```

this currently fails. observed in https://github.com/conda-forge/zensical-feedstock/issues/6 by @alexvoss

### PR DESCRIPTION
**Pull request by pavelzw**
closes #1982
closes #1928

### CODE REVIEW

File: src/packaging/file_mapper.rs [hunk 1]
```diff
@@ -72,7 +72,7 @@ pub fn filter_file(relative_path: &Path) -> bool {
     // filter any paths with .DS_Store, .git*, or conda-meta in them
     if relative_path.components().any(|c| {
         let s = c.as_os_str().to_string_lossy();
-        s.starts_with(".git") || s == ".DS_Store" || s == "conda-meta"
+        (s.starts_with(".git") && !s.starts_with(".github")) || s == ".DS_Store" || s == "conda-meta"
```
Comment (pavelzw) [inline src/packaging/file_mapper.rs]:
```suggestion
        s == ".DS_Store" || s == "conda-meta"
```

**Review by wolfv — APPROVED** [review]
