### PR TITLE
fix: relative git_url paths

### LINKED ISSUE #140: Relative paths with git url
It was reported that relative paths don't seem to work properly with the git source yet.

### PR DESCRIPTION
**Pull request by ruben-arts**
My bad there was no canonicalization of the path. 
closes #140

### CODE REVIEW

File: src/source.rs [hunk 1]
```diff
@@ -168,11 +168,21 @@ fn fetch_repo(repo: &Repository, refspecs: &[String]) -> Result<(), git2::Error>
...
+    source: &'a GitSrc,
+    cache_dir: &'a Path,
+    recipe_dir: &'a Path,
+) -> Result<PathBuf, SourceError> {
     // Create cache path based on given cache dir and name of the source package.
     let filename = match &source.git_url {
         GitUrl::Url(url) => url.path_segments().unwrap().last().unwrap().to_string(),
-        GitUrl::Path(path) => path.file_name().unwrap().to_string_lossy().to_string(),
+        GitUrl::Path(path) => recipe_dir
+            .join(path)
```
Comment (wolfv) [inline src/source.rs:180]: is this necessary? I think filename should also work on a relative path?
Or maybe one should find out if the path is relative first, and then run the `join` code?

Comment (wolfv) [reply src/source.rs:180]: Hmm, the docs say: "If path is absolute, it replaces the current path." -- in that case I guess I am fine with this code :)

**Review by wolfv — APPROVED** [review]
